Offline_Streaming/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^videos/', include( 'videostream.urls' ))
]

videostream/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *
from django.views.generic import DetailView, ListView
from django.views.generic.dates import *

from videostream.models import VideoCategory, Video
#from videostream.feeds import LatestStream


urlpatterns = [

    url(r'^category/(?P<slug>[-\w]+)/$', DetailView.as_view(
            model=VideoCategory, context_object_name='category'
        ), name='videostream_category_detail'),

    url(r'^categories/$', ListView.as_view(
            model=VideoCategory,
        ), name='videostream_category_list'),


    ## Date Based Views
    url(r'^latest/$', ArchiveIndexView.as_view(
            queryset=Video.objects.filter(is_public=True),
            date_field='publish_date',
        ), name='videostream_video_archive'),

    url(r'^(?P<year>\d{4})/(?P<month>\w+)/(?P<day>\d{1,2})/(?P<slug>[-\w]+)/$', 
        DateDetailView.as_view(
            queryset=Video.objects.filter(is_public=True),
            date_field='publish_date',
        ),
        name='videostream_video_detail'),

    url(r'^(?P<year>\d{4})/(?P<month>\w+)/(?P<day>\d{1,2})/$',
        DayArchiveView.as_view(
            queryset=Video.objects.filter(is_public=True),
            date_field='publish_date',
        ), name='videostream_video_day'),

    url(r'^(?P<year>\d{4})/(?P<month>\w+)/$',
        MonthArchiveView.as_view(
            queryset=Video.objects.filter(is_public=True),
            date_field='publish_date',
        ), name='videostream_video_month'),

    url(r'^(?P<year>\d{4})/$', YearArchiveView.as_view(
            queryset=Video.objects.filter(is_public=True),
            date_field='publish_date',
        ), name='videostream_video_year'),

]

# feeds = {
#     'latest':  LatestStream,        
# }

# urlpatterns += patterns('django.contrib.syndication.views',
#     (r'^feeds/(?P<url>.*)/$', 'feed', {'feed_dict': feeds}),
# )

videostream/models.py
# -*- coding: utf-8 -*-

from datetime import datetime

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# use Django-tagging for tags. If Django-tagging cannot be found, create our own
# I did not author this little snippet, I found it somewhere on the web,
# and cannot remember where exactly it was.
try:
    from tagging.fields import TagField
    tagfield_help_text = 'Separate tags with spaces, put quotes around multiple-word tags.'
except ImportError:
    class TagField(models.CharField):
        def __init__(self, **kwargs):
            default_kwargs = {'max_length': 255, 'blank': True}
            default_kwargs.update(kwargs)
            super(TagField, self).__init__(**default_kwargs)
        def get_internal_type(self):
            return 'CharField'
    tagfield_help_text = 'Django-tagging was not found, tags will be treated as plain text.'
# End tagging snippet


class VideoCategory(models.Model):
    """ A model to help categorize videos """
    title = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True,
        help_text="A url friendly slug for the category",
    )
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Video Categories"

    def __unicode__(self):
        return "%s" % self.title

    @models.permalink
    def get_absolute_url(self):
        return ('videostream_category_detail', [self.slug])


class Video(models.Model):
    """
    This is our Base Video Class, with fields that will be available
    to all other Video models.
    """
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,
        help_text="A url friendly slug for the video clip.")
    description = models.TextField(null=True, blank=True)

    tags = TagField(help_text=tagfield_help_text)
    categories = models.ManyToManyField(VideoCategory)
    allow_comments = models.BooleanField(default=False)

    ## TODO:
    ## In future we may want to allow for more control over publication
    is_public = models.BooleanField(default=False)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(null=True, blank=True)

    author = models.ForeignKey(User, null=True, blank=True)
    
    class Meta:
        ordering = ('-publish_date', '-created_date')
        get_latest_by = 'publish_date'

    def __unicode__(self):
        return "%s" % self.title

    @models.permalink
    def get_absolute_url(self):
        return ('videostream_video_detail', (), { 
            'year': self.publish_date.strftime("%Y"),
            'month': self.publish_date.strftime("%b"),
            'day': self.publish_date.strftime("%d"), 
            'slug': self.slug 
        })

    def save(self, *args, **kwargs):
        self.modified_date = datetime.now()
        if self.publish_date == None and self.is_public:
            self.publish_date = datetime.now()
        super(Video, self).save(*args, **kwargs)


class BasicVideo(Video):
    """
    This is our basic HTML5 Video type. BasicVideo can have more than
    one HTML5 Video as a 'video type'. This allows us to create different
    video formats, one for each type format.
    """
    pass


class HTML5Video(models.Model):
    OGG = 0
    WEBM = 1
    MP4 = 2
    FLASH = 3
    VIDEO_TYPE = (
        (OGG, 'video/ogg'),
        (WEBM, 'video/webm'),
        (MP4, 'video/mp4'),
        (FLASH, 'video/flv'),
    )

    video_type = models.IntegerField(
        choices=VIDEO_TYPE,
        default=WEBM,
        help_text="The Video type"
    )
    video_file = models.FileField(
        upload_to="videos/html5/",
        help_text="The file you wish to upload. Make sure that it's the correct format.",
    )

    # Allow for multiple video types for a single video
    basic_video = models.ForeignKey(BasicVideo)

    class Meta:
        verbose_name = "Html 5 Video"
        verbose_name_plural = "Html 5 Videos"


class EmbedVideo(Video):
    video_url = models.URLField(null=True, blank=True)
    video_code = models.TextField(
        null=True,
        blank=True,
        help_text="Use the video embed code instead of the url if your frontend does not support embedding with the URL only."
    )


class FlashVideo(Video):
    """
    This model is what was once called "VideoStream". Since we want to support
    videos from other sources as well, this model was renamed to FlashVideo.
    """
    original_file = models.FileField(
        upload_to="videos/flash/source/",
        null=True,
        blank=True,
        help_text="Make sure that the video you are uploading has a audo bitrate of at least 16. The encoding wont function on a lower audio bitrate."
    )

    flv_file = models.FileField(
        upload_to="videos/flash/flv/",
        null=True,
        blank=True,
        help_text="If you already have an encoded flash video, upload it here (no encoding needed)."
    )

    thumbnail = models.ImageField(
        blank=True,
        null=True, 
        upload_to="videos/flash/thumbnails/",
        help_text="If you uploaded a flv clip that was already encoded, you will need to upload a thumbnail as well. If you are planning use django-video to encode, you dont have to upload a thumbnail, as django-video will create it for you"
    )

    # This option allows us to specify whether we need to encode the clip
    encode = models.BooleanField(
        default=False,
        help_text="Encode or Re-Encode the clip. If you only wanted to change some information on the item, and do not want to encode the clip again, make sure this option is not selected."
    )

    def get_player_size(self):
        """ this method returns the styles for the player size """
        size = getattr(settings, 'VIDEOSTREAM_SIZE', '320x240').split('x')
        return "width: %spx; height: %spx;" % (size[0], size[1])

videostream/templates/videostream/include/render_video.html
{% load oembed_tags %}


{% if video_type == 'basicvideo' %}
    <video width="320" height="240" controls="controls">
        {% for video in video_instance.basicvideo.html5video_set.all %}
        <source src="{{ video.video_file.url }}" type="{{ video.get_video_type_display }}">
        {% endfor %}
        Your browser does not support the Video Tag.
    </video>
{% endif %}


{% if video_type == 'embedvideo' %}

    {% comment %}
    
        If we have the video_code, then we use that to embed the video.
        If not then we will use django-oembed to display the video directly
        from the url.
        Make sure you have django-oembed installed.

    {% endcomment %}

    {% if video_instance.embedvideo.video_code %}
        {{ video_instance.embedvideo.video_code|safe }}
    {% else %}
        {% oembed %}{{ video_instance.embedvideo.video_url }}{% endoembed %}
    {% endif %}

{% endif %}


{% if video_type == 'flashvideo' %}

    {% comment %}
        To use the flashplayer option, you need to have a flashplayer installed
        for your site. FlowPlayer is a good choice (http://flowplayer.org/).

        If you have a flashplayer installed, you need to customize this
        template and add the neccesarry HTML required for the flash
        player you chose.

        Here is a example, using flowplayer:

        <a href="{{ video_instance.flashvideo.flv_file.url }}"
            style="display: block; width={{ width }}; height={{ height }};"
            id="player"> </a>
    {% endcomment %}

    <p>The player has been disabled in the demo app. See the template,
        <code>videostream/include/render_video.html</code>.

    <p>Just for reference, the flv file is: <code>{{ video_instance.flashvideo.flv_file.url }}</code>

{% endif %}

videostream/templates/videostream/video_archive.html
    <h1>Latest Videos</h1>

    <ul>
        {% for video in latest %}
        <li>
            <h2><a href="{{ video.get_absolute_url }}">{{ video.title }}</a></h2>
            <p>
                {% if video.author.get_full_name %}
                    {{ video.author.get_full_name }}
                {% else %}
                    {{ video.author }}
                {% endif %}
                - {{ video.publish_date|date:"d M Y" }}
            </p>
            <p>{{ video.description }}</p>
            <p><a href="{{ video.get_absolute_url }}">View now...</a></p>
        </li>
        {% endfor %}
    </ul>

videostream/templates/videostream/video_archive_day.html
    <h1>Videos for, {{ day|date:"d M Y" }}</h1>

    <ul>
        {% for video in object_list %}
        <li>
            <h2><a href="{{ video.get_absolute_url }}">{{ video.title }}</a></h2>
            <p>
                {% if video.author.get_full_name %}
                    {{ video.author.get_full_name }}
                {% else %}
                    {{ video.author }}
                {% endif %}
                - {{ video.publish_date|date:"d M Y" }}
            </p>
            <p>{{ video.description }}</p>
            <p><a href="{{ video.get_absolute_url }}">View now...</a></p>
        </li>
        {% endfor %}
    </ul>

videostream/templates/videostream/video_archive_month.html
    <h1>Videos published in, {{ month|date:"M Y" }}</h1>

    <ul>
        {% for video in object_list %}
        <li>
            <h2><a href="{{ video.get_absolute_url }}">{{ video.title }}</a></h2>
            <p>
                {% if video.author.get_full_name %}
                    {{ video.author.get_full_name }}
                {% else %}
                    {{ video.author }}
                {% endif %}
                - {{ video.publish_date|date:"d M Y" }}
            </p>
            <p>{{ video.description }}</p>
            <p><a href="{{ video.get_absolute_url }}">View now...</a></p>
        </li>
        {% endfor %}
    </ul>

videostream/templates/videostream/video_archive_year.html
    <h1>Videos published in, {{ year }}</h1>

    <ul>
        {% for month in date_list %}
        <li><a href="{% url 'videostream_video_month' month|date:"Y" month|date:"b" %}">
            {{ month|date:"F" }}</a></li>
        {% endfor %}
    </ul>

videostream/templates/videostream/video_detail.html
{% load videostream_tags %}

{% if video %}

    <h1>{{ object.title }}</h1>
    <p>{{ object.description }}</p>

    {% render_video object %}

{% endif %}

videostream/templates/videostream/videocategory_detail.html
<h1>{{ category }}</h1>

videostream/templates/videostream/videocategory_list.html
{% for cat in category_list %}
    <h1>{{ cat }}</h1>
{% endfor %}